import type { NextPage } from 'next'
import Head from 'next/head'
import { Profile } from '../components/profile'


const Home: NextPage = () => {
  return (
  <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full">
       <Profile/>
      </main>    
      </>

  )
}

export default Home
